### PR TITLE
Fix timeline

### LINKED ISSUE #169: prepare_for_timelineA() with default arguments creates an incorrect visual
When rendering README I noticed that when running prepare_for_timelineA() with only necessary arguments specified I obtain a visual that is incorrect (see image below).

image

The correct visual should be similar to this one (without the dashed lines potentially):

image

### PR DESCRIPTION
**Pull request by MonikaFu**
Closes #169 

In this PR I add a helper to find the correct start year for the timeline plot.

### CODE REVIEW

File: R/prep_timeline.R [hunk 1]
```diff
@@ -39,15 +39,17 @@ prep_timelineA <- function(sda_data,
...
+                           year_start = NULL,
+                           year_end = NULL,
                            column_line_names = "emission_factor_metric",
                            value_to_plot = "emission_factor_value",
                            extrapolate_missing_values = FALSE) {
   sda_data$sector <- tolower(sda_data$sector)
   sector_filter <- tolower(sector_filter)
   abort_bad_sector(sector_filter)
   warn_sector(sda_data, sector_filter)
+  year_start <- year_start %||% get_common_start_year(sda_data, column_line_names)
```
Comment (maurolepore) [inline R/prep_timeline.R:51]: Beautiful name!

File: R/prep_timeline.R [hunk 2]
```diff
@@ -239,3 +241,13 @@ prep_timelineB <- function(data, extrapolate = FALSE) {
...
+
+get_common_start_year <- function(data, column_line_names) {
+  year <- max(
+    data %>%
+      group_by(.data[[column_line_names]]) %>%
+      summarise(year = min(.data$year)) %>%
+      pull(.data$year)
+  )
+  year
+}
```
Comment (maurolepore) [inline R/prep_timeline.R:253]: Suggested rewrite (not tested):

```r
get_common_start_year <- function(data, column_line_names) {
  data %>%
    group_by(.data[[column_line_names]]) %>%
    summarise(year = min(.data$year)) %>%
    pull(.data$year) %>%
    max()
}
```

**Review by maurolepore — APPROVED** [review]
LGTM.
